name: "🐛 Bug report"
description: "Report an issue to help us improve the project"
title: "[BUG] <write a small description here>"
labels: ["bug, invalid"]

body:
  - type: textarea
    id: bug_description
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    id: bug_expected
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen"
    validations:
      required: true
  - type: textarea
    id: bug_screenshots
    attributes:
      label: "Screenshots/Video"
      description: "Please add screenshots or a video to know more about the bug issue"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here"
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "What browser are you seeing the problem on?"
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Brave
  - type: checkboxes
    id: checklist_bug_issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)"
          required: true

        - label: "I will work on this issue (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false
