name: "💡 Feature request"
description: "Have a new idea/feature ? Please suggest!"
title: "[FEATURE] <write a small description here>"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: "Description"
      description: A clear and concise description of any alternative solution or features you've considered.
    validations:
      required: true
  - type: textarea
    id: feature_solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: feature_alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: feature_extrainfo
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
  - type: checkboxes
    id: checklist_feature_issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing [issues](https://github.com/Bookingjini-Labs/bookingjini-icons/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/Bookingjini-Labs/bookingjini-icons/blob/dev/CONTRIBUTING.md)"
          required: true

        - label: "I will work on this issue (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false
